---
ignore: |
  *.sops.*
  gotk-components.yaml
  gotk-sync.yaml
extends: default
rules:
  truthy:
    allowed-values: ["true", "false"]
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 80
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: consistent
