apiVersion: v1
kind: Secret
type: Opaque
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    USER_EMAIL: ENC[AES256_GCM,data:gZ3+NS3iFnJeMj0uappZHBurpbK/N46dmMY=,iv:p44QjSQCZUaR59bKo/byduqmKWC/cIDMmqrHvpbmp6c=,tag:QideIZLqurUcW2hzSvqGGQ==,type:str]
    CF_EMAIL: ENC[AES256_GCM,data:/R3P+RhwNYUXAhHVseZ5/AqbhQ==,iv:ll5ROixXJCFWeUhYW8P36YjGFPv6ZTHWfaURYhU9JyA=,tag:Jbc0N1rhr7K1uN0y1johqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-11T16:13:52Z"
    mac: ENC[AES256_GCM,data:DtMlxjq4FdoR04zJB2iF2TkXnB8c9w63arrhm4aF2NpBQtOoNZyHZnNKiLgYvtXw2kIVqALdScieLOthjC7h5HH8H/NTkIobE9E2gXOrpAjb7FE4HipC1ciYnNV+mGj7/PFI/JgCiDcoKhGl5RbOZ2T8xK+1hSNDSUMuVna1w1I=,iv:dwqtwybA5VrJb3yXHdBEFmpKy2yP6uyqqLZpCy1BZ4s=,tag:cEnfuhvM3cni7HfvWcJiIA==,type:str]
    pgp:
        - created_at: "2021-10-11T16:13:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7u9ZptfG2LzAQ//S+RlRtfoDuGiV3rrxHRK9AagHqOPTvaYP20cI9nCLwup
            dvCs7cHfZcxjNEG8DBa6u6sGqfiv8oKN771lxVk+ejmsQYcj6sg4gaRFGtfhtxSX
            3DiIaSZ1mgIP2zHW7Kir+mB4XEYT3v6QGqSVO496wQmXPzB04FCisaym9hmqef6a
            d0LhW1GSjjey/RqVLozlLIf31GfyROA+b5OIo/7RTrg5uPcOK/fJ4M3/scVwk0d5
            3M7D+xsxxA8G3snCjHV561ZOR+EPvNrJu/sun5sv/yw89Lg7hAwU70hw34JfSs4M
            goME4Yy79jrvq2hLrKinwpFXK3KtkoL3YxEk/NLv21X3ZNauUdGhDTLyAuPLA7vX
            lzg2queZGTj2VjilnXO4xSL22NUKR4sj0cdY1vy3ORIN/KPq1EKxvCdDxtG4CyVC
            V7L6Xz9MjudSlbGibEJExjs33tEKYbY8IC7V7WrMceeVEQ1pfQPAGTW1cijLbtKx
            595R0qa31qGp5RWqYtTCoZxKsyCNVxE6XT5Z65dbGhXp6zZjkPFilZO+ZFg4TEXO
            bxTdcYVYX/cn6E5VKz/NFEGYJt8TZf9rIUsXja1iipWvazHto/MxrUE2W1cfpKJp
            JI0tX3UMDecQpdTLGOUwfu533o58z7KtJhUxJlUdiJwWeaEacETcKM0rAqHzjfLU
            aAEJAhXsC3xXYjKUXiCtM3S0ym1+3r9fL0SjbzI3eVNzJRKhLSGTkwpdY9gvtySK
            FT3AuT/QbAZSq1eziiWQh/ibwweFVD9FONVp29TeDOTgmkkrNIxf00hyaLcen6tu
            kJs1oicwTmnK
            =YIwA
            -----END PGP MESSAGE-----
          fp: F87EE91C12866F36C1CC99E88606529B1E68B608
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
