---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-core
  namespace: flux-system
spec:
  dependsOn:
    # - name: cluster-crds
    - name: cluster-namespaces
    - name: cluster-operators
  interval: 10m0s
  path: ./cluster/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
