---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kube-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.0.30-192.168.0.35
