---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
    # renovate: registryUrl=https://metallb.github.io/metallb
    chart: metallb
    version: 0.10.2
    sourceRef:
      kind: HelmRepository
      name: metallb
      namespace: flux-system
  values:
    existingConfigMap: config
    prometheus:
      podMonitor:
        enabled: true
    controller:
      enabled: true
      image:
        repository: quay.io/metallb/controller
        tag: v0.10.2
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.10.2
      resources:
        limits:
          cpu: 100m
          memory: 100Mi