---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: ${USER_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateSecretKeyRef:
      name: personal-acme-key
    solvers:
    - dns01:
        cloudflare:
          email: ${CF_EMAIL}
          apiTokenSecretRef:
            name: cloudflare-token
            key: api-token
            